### ISSUE TITLE
In shares and targets on creating or modifying the share is not listing the 'users and groups'

### ISSUE THREAD

**Issue by naveen-fractlio** [fractalio/integralstor-gridcell#102]
On creating or modifying any shares its 'not listing' any of the users and groups available. 

Recreating steps:
Under Shares and targets tab;
create a share >> NO 'permitted users' and 'groups'

screenshot:

![screenshot from 2016-01-01 16-04-33](https://cloud.githubusercontent.com/assets/11418556/12070557/0b92e902-b0a2-11e5-94e4-2c7025330235.png)

Under share and targets tab;
view shares >> Details(select any of the share) >> Modify this share >> NO 'allowed users' and 'groups'

screenshot:

![screenshot from 2016-01-01 16-01-29](https://cloud.githubusercontent.com/assets/11418556/12070559/19e3b86a-b0a2-11e5-8804-fe0458a60f97.png)

**Comment by fractalram** [comment]
This was because the auth method was set to AD and the AD server was down..
