### ISSUE TITLE
Services management code needs exception handling

### ISSUE THREAD

**Issue by fractalram** [fractalio/integralstor-gridcell#103]
The view does not have any exception handling..

**Comment by fractalram** [comment]
We also should move the code to retrieve services status to a utility function in the site-packages/integralstor_gridcell dir. That way, I can call the function the get services info to display on the dashboard page. Now there is no way to do that without duplicating code..

**Comment by ramaseshan** [comment]
Added a services.py to gridcell site-packages, that now allows us to do any action on any service on all the nodes.
