### ISSUE TITLE
Installation Error- "1st time setup error"  

### ISSUE THREAD

**Issue by naveen-fractlio** [fractalio/integralstor-gridcell#104]
After fresh instaalation, when we run first time setup its giving error saying "Error setting up the gridcell system: error adding IPs to the CTDB nodes file....."

scrrenshots attached:
![screenshot from 2016-01-04 15-58-19](https://cloud.githubusercontent.com/assets/11418556/12088198/181f35f4-b2ff-11e5-8384-f02a35eb3175.png)
![screenshot from 2016-01-04 15-58-29](https://cloud.githubusercontent.com/assets/11418556/12088199/1846e130-b2ff-11e5-845d-e2e32974667e.png)

**Comment by fractalram** [comment]
Have checked in the fix. Please take a pull before the next install..

**Comment by fractalram** [comment]
Working now so closing
