### ISSUE TITLE
INSTALL - change the way the hosts file is created

### ISSUE THREAD

**Issue by fractalram** [fractalio/integralstor-gridcell#90]
We should not create the /etc/hosts file with ONLY one line of the form : 

127.0.0.1 localhost gridcell-1823 gridcell-1823.integralstor.lan

**Comment by naveen-fractlio** [comment]
From now we are creating /etc/hosts file with Only one line "127.0.0.1 localhost gridcell-1823 gridcell-1823.integralstor.lan"
