### ISSUE TITLE
INSTALL - Rename gluster scripts..

### ISSUE THREAD

**Issue by fractalram** [fractalio/integralstor-gridcell#93]
After we install gluster, at the end of the post section, we should add the following : 

mv /var/lib/glusterd/hooks/1/start/post/S29CTDBsetup.sh /var/lib/glusterd/hooks/1/start/post/unused_S29CTDBsetup.sh

mv /var/lib/glusterd/hooks/1/start/post/S30samba-start.sh /var/lib/glusterd/hooks/1/start/post/unused_S30samba-start.sh

mv /var/lib/glusterd/hooks/1/stop/pre/S29CTDB-teardown.sh /var/lib/glusterd/hooks/1/stop/pre/unused_S29CTDB-teardown.sh
mv /var/lib/glusterd/hooks/1/stop/pre/S30samba-stop.sh /var/lib/glusterd/hooks/1/stop/pre/unused_S30samba-stop.sh

mv /var/lib/glusterd/hooks/1/set/post/S30samba-set.sh /var/lib/glusterd/hooks/1/set/post/unused_S30samba-set.sh

**Comment by fractalram** [comment]
Is this fixed? Pl. mard as fixed if it is..

**Comment by naveen-fractlio** [comment]
All gluster files mentioned above are successfully moved to respective Directories("unused_.....").
