### ISSUE TITLE
Need to add "Processing screen" for long runnung processes

### ISSUE THREAD

**Issue by naveen-fractlio** [fractalio/integralstor-gridcell#96]

**Comment by ramaseshan** [comment]
Now to any page that requires a "Processing " page, just add the "cover-page" to the class of that element. and that should handle the process.
Ex :  <button type="submit" class="btn btn-primary **cover-page**">Save</button>

**Comment by ramaseshan** [comment]
Feel Free to add it any page, that requires this action.

**Comment by naveen-fractlio** [comment]
"cover-page" class is added to all "submit" types wherever we need apart from "processing" model.

**Comment by naveen-fractlio** [comment]
Now after new build, the "processing" screen is working fine and the same is removed for the 'download' pages.
