### ISSUE TITLE
INSTALL - Need to add config backup script to the gridcell ks file

### ISSUE THREAD

**Issue by fractalram** [fractalio/integralstor-gridcell#97]
We need to add this to the gridcell ks file : "chmod 755 /opt/integralstor/integralstor_gridcell/scripts/shell/*.sh"

Need to append the following line to the crontab file for all gridcell nodes : 

00 02 * * * /opt/integralstor/integralstor_gridcell/scripts/shell/config_backup.sh > /tmp/out_config_backup >> /tmp/err_config_backup

**Comment by fractalram** [comment]
Is this fixed? Pl. mard as fixed if it is..

**Comment by naveen-fractlio** [comment]
Its fixed need to validate after new install...

**Comment by naveen-fractlio** [comment]
File permissions for /opt/integralstor/integralstor_gridcell/scripts/shell/*.sh are changed to 755 after install and the crontab file updated for "config_backup.sh"
