### ISSUE TITLE
Error starting new volume created

### ISSUE THREAD

**Issue by naveen-fractlio** [fractalio/integralstor-gridcell#98]
After creating the new volume and to start, its giving error " Error starting volume

Error Details : An underlying storage operation has locked a volume so we are unable to process this request. Please try after a couple of seconds " 

Error Reproduce steps:
Create a volume >> Next >> Next >> Next >> Create >> You must first 'start the volume' before using it. >> Start this volume >> Error starting volume!

* I abserved after some time actually it is started!!!

* Once we start the volume "volume configuration" page showing nothing except success message. Here with succeess message the "volume configuration's" also need to be updated immediatly...

screenshot:

![screenshot from 2015-12-30 15-37-11](https://cloud.githubusercontent.com/assets/11418556/12049368/2dde879c-af0c-11e5-8cab-824871b30009.png)

**Comment by fractalram** [comment]
This happens when some other operation is accessing glusterd at the same time so we cannot do anything about it. The error message actually tells you to try again so shd be ok.
