### ISSUE TITLE
INSTALL - Need to install the Marvell driver in gridcell also

### ISSUE THREAD

**Issue by fractalram** [fractalio/integralstor-gridcell#99]
Need to do all the steps needed to install the Marvell drivers just like we do for unicell.. 

As part of this, please go through the latest unicell ks file and compare against the gridcell ks file to see if we have forgotten anything else.

**Comment by naveen-fractlio** [comment]
after install we have the marvel kernel installed and copied to the location: /lib/modules/2.6.32-504.el6.x86_64/extra/mv94xx/mv94xx.ko
